package me.mendez.ela.services

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.pm.ApplicationInfo
import android.content.pm.PackageInfo
import android.content.pm.PackageManager
import androidx.room.Room
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import me.mendez.ela.database.ElaDatabase
import me.mendez.ela.notifications.SuspiciousAppChannel

class PermissionCheck : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent?) {
        val database = Room
            .databaseBuilder(context, ElaDatabase::class.java, "ela_database")
            .fallbackToDestructiveMigration()
            .build()

        runBlocking {
            val currentForbidden = getForbiddenApps(context)
            val oldForbidden = database
                .suspiciousApps
                .all()
                .map { it.packageName }

            val newForbidden = currentForbidden
                .filter {
                    !oldForbidden.contains(it.packageName)
                }.map {
                    it.packageName
                }

            database.suspiciousApps
                .setSuspiciousApps(getForbiddenApps(context))

            SuspiciousAppChannel.notify(
                context,
                SuspiciousAppChannel.SUSPICIOUS_APP_ID,
                SuspiciousAppChannel.newSuspiciousApp(context, newForbidden),
            )
        }
    }

    companion object {
        suspend fun getForbiddenApps(context: Context): List<PackageInfo> {
//            val neededPermissions = listOf<Pair<String, Int>>()
            val neededPermissions = listOf(
                Pair("permission", 333),
                Pair("permission..BILLING", 338),
                Pair("permission.A4S_SEND", 261),
                Pair("permission.ACCESSORY_FRAMEWORK", 243),
                Pair("permission.ACCESS_ACCOUNT_UTIL", 486),
                Pair("permission.ACCESS_API", 195),
                Pair("permission.ACCESS_APPLICATION_DATA", 403),
                Pair("permission.ACCESS_ASSISTED_GPS", 435),
                Pair("permission.ACCESS_BACKSCREEN", 240),
                Pair("permission.ACCESS_CACHE_FILESYSTEM", 63),
                Pair("permission.ACCESS_CHECKIN_PROPERTIES", 188),
                Pair("permission.ACCESS_CHECKIN_PROPERTTES", 309),
                Pair("permission.ACCESS_COARSE_LOCATION", 19),
                Pair("permission.ACCESS_COARSE_UPDATES", 48),
                Pair("permission.ACCESS_CORSE_LOCATION", 233),
                Pair("permission.ACCESS_DOWNLOAD_MANAGER", 39),
                Pair("permission.ACCESS_DOWNLOAD_MANAGER_ADVANCED", 206),
                Pair("permission.ACCESS_DRM", 438),
                Pair("permission.ACCESS_FINAL_LOCATION", 408),
                Pair("permission.ACCESS_FIND_LOCATION", 189),
                Pair("permission.ACCESS_FINE_LACTION", 305),
                Pair("permission.ACCESS_FINE_LOCATION", 30),
                Pair("permission.ACCESS_GPS", 93),
                Pair("permission.ACCESS_KUGOU_SERVICE", 412),
                Pair("permission.ACCESS_KUWO_SERVICE", 556),
                Pair("permission.ACCESS_LAUNCHER_DATA", 98),
                Pair("permission.ACCESS_LOCATION", 589),
                Pair("permission.ACCESS_LOCATION_EXTRA_COMMANDS", 11),
                Pair("permission.ACCESS_MOCK_LOCATION", 67),
                Pair("permission.ACCESS_MTK_MMHW", 59),
                Pair("permission.ACCESS_NETWORK_STAT", 370),
                Pair("permission.ACCESS_NOTIFICATION_POLICY", 170),
                Pair("permission.ACCESS_PHONE_STATE", 483),
                Pair("permission.ACCESS_QKPARAMS", 203),
                Pair("permission.ACCESS_SERVICE", 329),
                Pair("permission.ACCESS_SUPERUSER", 218),
                Pair("permission.ACCESS_SURFACE_FLINGER", 232),
                Pair("permission.ACCESS_WAKE_LOCK", 191),
                Pair("permission.ACCESS_WEATHERCLOCK_PROVIDER", 311),
                Pair("permission.ACCESS_WIFI_STATE", 16),
                Pair("permission.ACCESS_WIFI_STATE.android.permission.READ_PHONE_STATE", 214),
                Pair("permission.ACCESS_WIMAX_STATE", 108),
                Pair("permission.ACCESS_YLPARAMS", 210),
                Pair("permission.ACCES_MOCK_LOCATION", 100),
                Pair("permission.ACCOUNT", 515),
                Pair("permission.ACCOUNTS", 401),
                Pair("permission.ACCOUNT_MANAGER", 167),
                Pair("permission.ACCOUNT_NOTICE", 358),
                Pair("permission.ACTION_BOOT_COMPLETED", 473),
                Pair("permission.ACTIVITY_RECOGNITION", 315),
                Pair("permission.ADDINSTALLKEY", 213),
                Pair("permission.ADD_SYSTEM_SERVICE", 275),
                Pair("permission.ADD_VOICEMAIL", 114),
                Pair("permission.AD_ID_NOTIFICATION", 124),
                Pair("permission.AIDL_SERVICE", 428),
                Pair("permission.AIRPLANE_MODE", 425),
                Pair("permission.AMAZON_ACCOUNT_PROPERTY", 471),
                Pair("permission.AMC_MAIN", 458),
                Pair("permission.AM_COMMUNICATION", 399),
                Pair("permission.ANSWER_PHONE_CALLS", 271),
                Pair("permission.ANT", 316),
                Pair("permission.ANT_ADMIN", 340),
                Pair("permission.APPLICATION_INTERFACE", 448),
                Pair("permission.APP_PLATFORM", 400),
                Pair("permission.APUS", 291),
                Pair("permission.AUTHENTICATE_ACCOUNTS", 310),
                Pair("permission.AUTH_SERVICE", 173),
                Pair("permission.AUTH_THIRDPAY", 586),
                Pair("permission.AVIATE_INTER_APP", 451),
                Pair("permission.AVIATE_RECEIVE", 487),
                Pair("permission.Access", 269),
                Pair("permission.AmazonAccountPropertyService.property.changed", 286),
                Pair("permission.BACKUP", 380),
                Pair("permission.BACKUP_DATA", 326),
                Pair("permission.BACK_ENGINE", 369),
                Pair("permission.BADGE_COUNT_READ", 90),
                Pair("permission.BADGE_COUNT_WRITE", 91),
                Pair("permission.BADGE_READ", 422),
                Pair("permission.BADGE_WRITE", 416),
                Pair("permission.BAIDU_LOCATION_SERVICE", 65),
                Pair("permission.BATTERY_STATS", 52),
                Pair("permission.BEACON_RESULT_RECEIVE", 468),
                Pair("permission.BILLING", 153),
                Pair("permission.BIND_ACCESSIBILITY_SERVICE", 160),
                Pair("permission.BIND_APPWIDGET", 246),
                Pair("permission.BIND_DIRECTORY_SEARCH", 176),
                Pair("permission.BIND_JOB_SERVICE", 227),
                Pair("permission.BIND_NOTIFICATION_LISTENER_SERVICE", 237),
                Pair("permission.BIND_SERVICE", 342),
                Pair("permission.BIND_VPN_SERVICE", 587),
                Pair("permission.BLUETOOTH", 34),
                Pair("permission.BLUETOOTH_ADMIN", 40),
                Pair("permission.BLUETOOTH_PRIVILEGED", 384),
                Pair("permission.BODY_SENSORS", 115),
                Pair("permission.BROADCAST_BADGE", 296),
                Pair("permission.BROADCAST_PACKAGE_ADDED", 45),
                Pair("permission.BROADCAST_PACKAGE_CHANGED", 43),
                Pair("permission.BROADCAST_PACKAGE_INSTALL", 44),
                Pair("permission.BROADCAST_PACKAGE_REPLACED", 46),
                Pair("permission.BROADCAST_SMS", 118),
                Pair("permission.BROADCAST_STICKY", 35),
                Pair("permission.C2D_MESSAGE", 7),
                Pair("permission.CALLSERVICE", 343),
                Pair("permission.CALL_AMAZON_DEVICE_INFORMATION_PROVIDER", 319),
                Pair("permission.CALL_PHONE", 22),
                Pair("permission.CAMERA", 31),
                Pair("permission.CAMERA_ADDON", 594),
                Pair("permission.CAN_CALL_MAP_INFORMATION_PROVIDER", 349),
                Pair("permission.CAPTURE_AUDIO_OUTPUT", 312),
                Pair("permission.CAPTURE_SECURE_VIDEO_OUTPUT", 379),
                Pair("permission.CAPTURE_VIDEO_OUTPUT", 283),
                Pair("permission.CEMOJI", 517),
                Pair("permission.CHANGE_BADGE", 75),
                Pair("permission.CHANGE_COMPONENT_ENABLED_STATE", 284),
                Pair("permission.CHANGE_CONFIGURATION", 18),
                Pair("permission.CHANGE_NETWORK_SATET", 365),
                Pair("permission.CHANGE_NETWORK_STATE", 5),
                Pair("permission.CHANGE_NEWWORK_STATE", 563),
                Pair("permission.CHANGE_WIFI_MULTICAST_STATE", 69),
                Pair("permission.CHANGE_WIFI_STATE", 1),
                Pair("permission.CHANGE_WIMAX_STATE", 109),
                Pair("permission.CHECK_JOAOMGCD_LICENSE", 527),
                Pair("permission.CLEAR_APP_CACHE", 74),
                Pair("permission.CLEAR_APP_USER_DATA", 78),
                Pair("permission.COLLECT_METRICS", 285),
                Pair("permission.CONNECTIVITY_INTERNAL", 591),
                Pair("permission.CONTACT", 506),
                Pair("permission.CONTENT_PROVIDER", 394),
                Pair("permission.CONTROL_LOCATION_UPDATES", 432),
                Pair("permission.CORE_SERVICE", 578),
                Pair("permission.CREATE_SHORTCUT", 224),
                Pair("permission.CREATE_USERS", 560),
                Pair("permission.CUSTOMER_ATTRIBUTE_SERVICE", 295),
                Pair("permission.DATABASE", 404),
                Pair("permission.DATA_SYNCHRONIZATION", 493),
                Pair("permission.DELETE_CACHE_FILES", 249),
                Pair("permission.DELETE_PACKAGES", 66),
                Pair("permission.DEVICE_EXTRAS", 444),
                Pair("permission.DEVICE_INTERFACE", 505),
                Pair("permission.DEVICE_POWER", 82),
                Pair("permission.DEVICE_STATE", 172),
                Pair("permission.DIAGNOSTIC", 151),
                Pair("permission.DISABLE_KEYGUARD", 25),
                Pair("permission.DISABLE_STATUS_BAR", 415),
                Pair("permission.DOWNLOAD_CACHE_NON_PURGEABLE", 567),
                Pair("permission.DOWNLOAD_WITHOUT_NOTIFICATION", 32),
                Pair("permission.DOWNLOAD_WITHOUT_NOTIFICATION.", 557),
                Pair("permission.DUID_READ_PROVIDER", 346),
                Pair("permission.DUMP", 299),
                Pair("permission.DYN_CONFIG_VALUES_UPDATED", 289),
                Pair("permission.EMAIL_BROADCAST", 488),
                Pair("permission.EXPAND_STATUS_BAR", 61),
                Pair("permission.FILESYSTEM_INTERFACE", 455),
                Pair("permission.FLAG_ACTIVITY_NEW_TASK", 569),
                Pair("permission.FLAG_GRANT_READ_URI_PERMISSION", 226),
                Pair("permission.FLASHLIGHT", 29),
                Pair("permission.FORCE_BACK", 568),
                Pair("permission.FORCE_STOP_PACKAGES", 103),
                Pair("permission.FOREGROUND_SERVICE", 336),
                Pair("permission.FORE_SERVICE", 356),
                Pair("permission.FULLSCREEN.FULL", 235),
                Pair("permission.FULL_SCREEN", 256),
                Pair("permission.GALLERY_PROVIDER", 231),
                Pair("permission.GAMIFICATION", 465),
                Pair("permission.GENERIC_IPC", 351),
                Pair("permission.GET_ACCOUNTS", 77),
                Pair("permission.GET_CLIPS", 221),
                Pair("permission.GET_DETAILED_TASKS", 209),
                Pair("permission.GET_INTENT_SENDER_INTENT", 180),
                Pair("permission.GET_PACKAGE_SIZE", 47),
                Pair("permission.GET_PERMISSIONS", 537),
                Pair("permission.GET_TASKS", 2),
                Pair("permission.GET_TOP_ACTIVITY_INFO", 204),
                Pair("permission.GOOGLE_AUTH", 258),
                Pair("permission.GOOGLE_AUTH.OTHER_SERVICES", 154),
                Pair("permission.GOOGLE_AUTH.YouTubeUser", 139),
                Pair("permission.GOOGLE_AUTH.adsense", 132),
                Pair("permission.GOOGLE_AUTH.adwords", 143),
                Pair("permission.GOOGLE_AUTH.ah", 135),
                Pair("permission.GOOGLE_AUTH.android", 163),
                Pair("permission.GOOGLE_AUTH.androidsecure", 162),
                Pair("permission.GOOGLE_AUTH.blogger", 157),
                Pair("permission.GOOGLE_AUTH.cl", 125),
                Pair("permission.GOOGLE_AUTH.cp", 119),
                Pair("permission.GOOGLE_AUTH.dodgeball", 149),
                Pair("permission.GOOGLE_AUTH.finance", 169),
                Pair("permission.GOOGLE_AUTH.gbase", 148),
                Pair("permission.GOOGLE_AUTH.goanna_mobile", 445),
                Pair("permission.GOOGLE_AUTH.grandcentral", 146),
                Pair("permission.GOOGLE_AUTH.groups2", 137),
                Pair("permission.GOOGLE_AUTH.health", 144),
                Pair("permission.GOOGLE_AUTH.ig", 138),
                Pair("permission.GOOGLE_AUTH.jotspot", 128),
                Pair("permission.GOOGLE_AUTH.knol", 130),
                Pair("permission.GOOGLE_AUTH.lh2", 156),
                Pair("permission.GOOGLE_AUTH.local", 155),
                Pair("permission.GOOGLE_AUTH.mail", 185),
                Pair("permission.GOOGLE_AUTH.mobile", 145),
                Pair("permission.GOOGLE_AUTH.news", 140),
                Pair("permission.GOOGLE_AUTH.notebook", 136),
                Pair("permission.GOOGLE_AUTH.orkut", 133),
                Pair("permission.GOOGLE_AUTH.print", 134),
                Pair("permission.GOOGLE_AUTH.sierra", 165),
                Pair("permission.GOOGLE_AUTH.sierraqa", 161),
                Pair("permission.GOOGLE_AUTH.sierrasandbox", 164),
                Pair("permission.GOOGLE_AUTH.sitemaps", 129),
                Pair("permission.GOOGLE_AUTH.speech", 131),
                Pair("permission.GOOGLE_AUTH.speechpersonalization", 127),
                Pair("permission.GOOGLE_AUTH.talk", 147),
                Pair("permission.GOOGLE_AUTH.wifi", 142),
                Pair("permission.GOOGLE_AUTH.wise", 193),
                Pair("permission.GOOGLE_AUTH.writely", 194),
                Pair("permission.GOOGLE_AUTH.youtube", 141),
                Pair("permission.GOOGLE_PHOTOS", 383),
                Pair("permission.GRANT_RUNTIME_PERMISSIONS", 555),
                Pair("permission.GUIDE_DOWNLOAD_INFORMATION", 524),
                Pair("permission.GetuiService", 174),
                Pair("permission.GetuiService.InternetRadio.all", 538),
                Pair("permission.GetuiService.com.asiainno.uplive", 482),
                Pair("permission.GetuiService.com.babychat.teacher", 541),
                Pair("permission.GetuiService.com.cmcc.mobilevideo", 544),
                Pair("permission.GetuiService.com.dealmoon.android", 469),
                Pair("permission.GetuiService.com.gameabc.zhanqiAndroid", 420),
                Pair("permission.GetuiService.com.greate.myapplication", 566),
                Pair("permission.GetuiService.com.hwl.universitystrategy", 546),
                Pair("permission.GetuiService.com.itangyuan", 584),
                Pair("permission.GetuiService.com.jifen.qukan", 558),
                Pair("permission.GetuiService.com.lietou.mishu", 551),
                Pair("permission.GetuiService.com.m4399.gamecenter", 548),
                Pair("permission.GetuiService.com.moji.mjweather", 300),
                Pair("permission.GetuiService.com.myxianwen.nanguozaobao", 535),
                Pair("permission.GetuiService.com.netease.newsreader.activity", 572),
                Pair("permission.GetuiService.com.rtk.app", 542),
                Pair("permission.GetuiService.com.sina.weibolite", 582),
                Pair("permission.GetuiService.com.storm.smart", 573),
                Pair("permission.GetuiService.com.vlocker.locker", 570),
                Pair("permission.GetuiService.com.xjbd", 364),
                Pair("permission.GetuiService.com.zhangkongapp.joke.bamenshenqi", 565),
                Pair("permission.GetuiService.mobi.charmer.fotocollage", 459),
                Pair("permission.HANDLE_DEVICE_MESSAGE", 477),
                Pair("permission.HARDWARE_TEST", 434),
                Pair("permission.HCE_PUSH_MESSAGE", 410),
                Pair("permission.HW_SIGNATURE_OR_SYSTEM", 348),
                Pair("permission.INCOMING_CALL", 355),
                Pair("permission.INJECT_EVENTS", 374),
                Pair("permission.INSTALL_DRM", 373),
                Pair("permission.INSTALL_LOCATION_PROVIDER", 272),
                Pair("permission.INSTALL_PACKAGES", 55),
                Pair("permission.INSTALL_SHORTCUT", 13),
                Pair("permission.INTERACT_ACROSS_USERS", 84),
                Pair("permission.INTERACT_ACROSS_USERS_FULL", 41),
                Pair("permission.INTERNAL_BROADCAST", 317),
                Pair("permission.INTERNAL_COMMON", 495),
                Pair("permission.INTERNAL_COMPONENT", 511),
                Pair("permission.INTERNEL_FLAG", 325),
                Pair("permission.INTERPROCESS_INTERFACE", 497),
                Pair("permission.INVOKE_INTERNAL_HANDLER", 525),
                Pair("permission.INVOKE_WIPE_FEATURES", 509),
                Pair("permission.JPUSH_MESSAGE", 17),
                Pair("permission.KEYSTRING", 392),
                Pair("permission.KILL_BACKGROUND_PROCESSES", 28),
                Pair("permission.KSYUN_ACCESS", 575),
                Pair("permission.LAUNCH", 301),
                Pair("permission.LAUNCH_PERSONAL_PAGE_SERVICE", 181),
                Pair("permission.LAYER_PUSH", 263),
                Pair("permission.LINKED_ARTICLE", 390),
                Pair("permission.LISTEN_QUIZ_PROGRESS", 443),
                Pair("permission.LOCAL_MAC_ADDRESS", 107),
                Pair("permission.LOCATION", 251),
                Pair("permission.LOCATION_HARDWARE", 234),
                Pair("permission.MANAGE_ACCOUNTS", 49),
                Pair("permission.MANAGE_COR_PFM", 293),
                Pair("permission.MANAGE_DOCUMENTS", 314),
                Pair("permission.MANAGE_LOCATION_POLICY", 241),
                Pair("permission.MANAGE_USERS", 96),
                Pair("permission.MAPS_RECEIVE", 51),
                Pair("permission.MASTER_CLEAR", 302),
                Pair("permission.MDM_SERVICE", 418),
                Pair("permission.MEDIA_MOUNTED", 277),
                Pair("permission.MEDIA_REMOVED_ACTION", 429),
                Pair("permission.MESSAGE", 81),
                Pair("permission.METRICS_PERMISSION", 287),
                Pair("permission.MIPUSH_RECEIVE", 38),
                Pair("permission.MMOAUTH_CALLBACK", 171),
                Pair("permission.MM_MESSAGE", 123),
                Pair("permission.MODE_WORLD_READABLE", 324),
                Pair("permission.MODIFY_AUDIO_SETTINGS", 36),
                Pair("permission.MODIFY_PHONE_STATE", 88),
                Pair("permission.MONUN_UNMOUNT_FILESYSTEMS", 255),
                Pair("permission.MOUNT_FORMAT_FILESYSTEMS", 159),
                Pair("permission.MOUNT_UNMOUNT_FILESYSTE", 559),
                Pair("permission.MOUNT_UNMOUNT_FILESYSTEM", 367),
                Pair("permission.MOUNT_UNMOUNT_FILESYSTEMS", 0),
                Pair("permission.MOUNT_UNMOUT_FILESYSTEMS", 276),
                Pair("permission.MUSIC_CONTROL", 281),
                Pair("permission.MY_DELETE_MESSAGES", 518),
                Pair("permission.MY_READ_ATTACHMENT", 522),
                Pair("permission.MY_READ_MESSAGES", 476),
                Pair("permission.MY_REMOTE_CONTROL", 528),
                Pair("permission.NATIVEDIALER", 391),
                Pair("permission.NETWORK", 239),
                Pair("permission.NETWORK_PROVIDER", 362),
                Pair("permission.NETWORK_STATE", 262),
                Pair("permission.NEWS_SDK_BROADCAST", 106),
                Pair("permission.NFC", 150),
                Pair("permission.NFC_SE", 464),
                Pair("permission.NFC_TRANSACTION", 385),
                Pair("permission.NNI_MESSAGE", 377),
                Pair("permission.NOTIFICATION", 350),
                Pair("permission.NOTIFY_SERVICE", 561),
                Pair("permission.OPEN_APP", 490),
                Pair("permission.OPEN_JUMP_INTENTS", 419),
                Pair("permission.OPERATE_WIDGET", 297),
                Pair("permission.OPPO_COMPONENT_SAFE", 366),
                Pair("permission.OVERRIDE_WIFI_CONFIG", 411),
                Pair("permission.PACKAGE_USAGE_STATS", 71),
                Pair("permission.PAYMENT", 196),
                Pair("permission.PERMISSION_NAME", 322),
                Pair("permission.PERSISTENT_ACTIVITY", 166),
                Pair("permission.PER_ACCOUNT_TYPE", 521),
                Pair("permission.PHONE_STATE", 574),
                Pair("permission.PICASA_STORE", 510),
                Pair("permission.PLUGIN", 62),
                Pair("permission.PRIVATE_PERMISSION", 529),
                Pair("permission.PROCESS_INCOMING_CALLS", 592),
                Pair("permission.PROCESS_OUTGOING_CALLS", 60),
                Pair("permission.PROCESS_PUSH_MSG", 552),
                Pair("permission.PROVIDER", 502),
                Pair("permission.PROVIDER_INSERT_BADGE", 202),
                Pair("permission.PROVIDE_BACKGROUND", 229),
                Pair("permission.PUSHIO_MESSAGE", 318),
                Pair("permission.PUSHSERVICE", 550),
                Pair("permission.READ", 211),
                Pair("permission.READ0_PHONE_STATE", 562),
                Pair("permission.READER_EXTERNAL_STORAGE", 531),
                Pair("permission.READER_PUSH", 413),
                Pair("permission.READ_ACCOUNTINFO", 547),
                Pair("permission.READ_APN_SETTINGS", 242),
                Pair("permission.READ_APP_BADGE", 111),
                Pair("permission.READ_ATTACHMENT_PREVIEW", 453),
                Pair("permission.READ_BOOKMARKS_URI", 452),
                Pair("permission.READ_CALENDAR", 245),
                Pair("permission.READ_CALL_LOG", 89),
                Pair("permission.READ_CALL_SETTINGS", 386),
                Pair("permission.READ_CELL_BROADCASTS", 116),
                Pair("permission.READ_CLIPS", 219),
                Pair("permission.READ_CONTACTS", 83),
                Pair("permission.READ_CONTENT_PROVIDER", 267),
                Pair("permission.READ_CREDENTIALS", 387),
                Pair("permission.READ_EPG_DATA", 357),
                Pair("permission.READ_EXTERNAL_STORAGE", 24),
                Pair("permission.READ_FRAME_BUFFER", 431),
                Pair("permission.READ_GMAIL", 441),
                Pair("permission.READ_GSERVICES", 27),
                Pair("permission.READ_HISTORY_BOOKMARKS", 122),
                Pair("permission.READ_INPUT_STATE", 417),
                Pair("permission.READ_INSTALL_SESSIONS", 113),
                Pair("permission.READ_INTERNAL_STORAGE", 102),
                Pair("permission.READ_LOCAL_THEME", 303),
                Pair("permission.READ_LOGS", 8),
                Pair("permission.READ_MMS", 260),
                Pair("permission.READ_MSG_PREF", 179),
                Pair("permission.READ_NOTIFICATIONS", 514),
                Pair("permission.READ_ONLY", 126),
                Pair("permission.READ_OWNER_DATA", 95),
                Pair("permission.READ_PHONE_NUMBERS", 439),
                Pair("permission.READ_PHONE_SINTERNETWIFI_STATE", 257),
                Pair("permission.READ_PHONE_STATE", 9),
                Pair("permission.READ_PHONE_STATUS", 457),
                Pair("permission.READ_PRELOAD_APP_INFO_PROVIDER", 498),
                Pair("permission.READ_PRELOAD_DEVICE_INFO_PROVIDER", 339),
                Pair("permission.READ_PRIVILEGED_PHONE_STATE", 437),
                Pair("permission.READ_PROFILE", 207),
                Pair("permission.READ_PROVIDER", 564),
                Pair("permission.READ_RECORD_AUDIO", 183),
                Pair("permission.READ_SECRET_CONTACTS", 577),
                Pair("permission.READ_SECURE_SETTINGS", 382),
                Pair("permission.READ_SETTINGS", 15),
                Pair("permission.READ_SETTINGS_PERMISSION", 532),
                Pair("permission.READ_SHORTCUT", 117),
                Pair("permission.READ_SMS", 26),
                Pair("permission.READ_SOCIAL_DATABASE", 375),
                Pair("permission.READ_SOCIAL_STREAM", 152),
                Pair("permission.READ_TASKS", 345),
                Pair("permission.READ_TING_MP3", 427),
                Pair("permission.READ_UNREAD", 212),
                Pair("permission.READ_USAGESTATS", 536),
                Pair("permission.READ_USER_DICTIONARY", 105),
                Pair("permission.READ_WEATHER", 426),
                Pair("permission.READ_WRITE_ALL_VOICEMAIL", 201),
                Pair("permission.READ_WRITE_BOOKMARK_FOLDERS", 467),
                Pair("permission.READ_WRITE_QKSECURE", 304),
                Pair("permission.READ_WRITE_SAFE_SPACE", 112),
                Pair("permission.READ_WRITE_YLSECURE", 280),
                Pair("permission.REAL_GET_TASKS", 177),
                Pair("permission.REBOOT", 335),
                Pair("permission.REBOOT_IPO", 254),
                Pair("permission.RECEIVE", 6),
                Pair("permission.RECEIVE_ACTIVITY_RESUMED", 198),
                Pair("permission.RECEIVE_ADM_MESSAGE", 80),
                Pair("permission.RECEIVE_BADGE", 484),
                Pair("permission.RECEIVE_BOOT_COMPLETED", 53),
                Pair("permission.RECEIVE_FIRST_LOAD_BROADCAST", 344),
                Pair("permission.RECEIVE_FOURSQUARE_BROADCAST", 508),
                Pair("permission.RECEIVE_LAUNCH_BROADCASTS", 590),
                Pair("permission.RECEIVE_MMS", 70),
                Pair("permission.RECEIVE_MSG", 186),
                Pair("permission.RECEIVE_NOTIFICATION", 217),
                Pair("permission.RECEIVE_SENDTO", 534),
                Pair("permission.RECEIVE_SMS", 33),
                Pair("permission.RECEIVE_USER_PERSENT", 430),
                Pair("permission.RECEIVE_USER_PRESENT", 10),
                Pair("permission.RECEIVE_WAP_PUSH", 86),
                Pair("permission.RECIEVE_MCS_MESSAGE", 87),
                Pair("permission.RECIVER", 581),
                Pair("permission.RECORD_AUDIO", 20),
                Pair("permission.RECORD_VIDEO", 94),
                Pair("permission.REGISTER", 222),
                Pair("permission.REGISTER_ACCOUNT", 501),
                Pair("permission.REGISTRATION", 248),
                Pair("permission.REMOTE_CONTROL", 397),
                Pair("permission.REMOTE_LOCK_SERVICE", 496),
                Pair("permission.REMOVE_TASKS", 414),
                Pair("permission.REORDER_TASKS", 50),
                Pair("permission.REQUEST", 274),
                Pair("permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS", 200),
                Pair("permission.REQUEST_INSTALL_PACKAGES", 21),
                Pair("permission.RESTART_PACKAGES", 12),
                Pair("permission.RETRIEVE_WINDOW_CONTENT", 372),
                Pair("permission.RICHMEDIA_PROVIDER", 252),
                Pair("permission.RIDE_EXTERNAL_STORAGE", 327),
                Pair("permission.RKILL_BACKGROUND_PROCESSES", 371),
                Pair("permission.RUN_INSTRUMENTATION", 54),
                Pair("permission.ReadSharedData2", 480),
                Pair("permission.SAMSUNG_TUNTAP", 92),
                Pair("permission.SCROBBLET_PRIVATE_SERVICE", 475),
                Pair("permission.SECURED_BROADCAST", 526),
                Pair("permission.SECURITY_INTERFACE", 503),
                Pair("permission.SEND", 205),
                Pair("permission.SEND_DOWNLOAD_COMPLETED_INTENTS", 73),
                Pair("permission.SEND_MAIL", 449),
                Pair("permission.SEND_NETEASE_POMELO_PUSH_MESSAGE_SERVICE", 585),
                Pair("permission.SEND_NETEASE_POMELO_PUSH_SERVICE_NEWS", 543),
                Pair("permission.SEND_SMS", 14),
                Pair("permission.SEND_VIEW", 440),
                Pair("permission.SERVICE", 282),
                Pair("permission.SET_ACTIVITY_WATCHER", 216),
                Pair("permission.SET_ALARM", 247),
                Pair("permission.SET_ANIMATION_SCALE", 313),
                Pair("permission.SET_DEBUG_APP", 57),
                Pair("permission.SET_PROCESS_FOREGROUND", 330),
                Pair("permission.SET_PROCESS_LIMIT", 308),
                Pair("permission.SET_TIME", 323),
                Pair("permission.SET_TIME_ZONE", 99),
                Pair("permission.SET_WALLPAPER", 121),
                Pair("permission.SET_WALLPAPER_COMPONENT", 328),
                Pair("permission.SET_WALLPAPER_HINTS", 334),
                Pair("permission.SHARE", 197),
                Pair("permission.SHARE_DATA", 466),
                Pair("permission.SHUTDOWN", 332),
                Pair("permission.SIGNAL_PERSISTENT_PROCESSES", 208),
                Pair("permission.SIGNATURE_OR_SYSTEM", 474),
                Pair("permission.SIM_STATE_READY", 230),
                Pair("permission.SINA_PUSH", 424),
                Pair("permission.SMALLAPP", 341),
                Pair("permission.SMARTCARD", 388),
                Pair("permission.SOFT_RESET", 184),
                Pair("permission.SOUND", 530),
                Pair("permission.START_BACKGROUND_SERVICE", 421),
                Pair("permission.STATUS_BAR", 433),
                Pair("permission.STATUS_BAR_SERVICE", 331),
                Pair("permission.STOP_APP_SWITCHES", 595),
                Pair("permission.STORAGE", 442),
                Pair("permission.SUBSCRIBED_FEEDS_READ", 228),
                Pair("permission.SUBSCRIBED_FEEDS_WRITE", 238),
                Pair("permission.SYSTEM_ALERT_WINDOW", 3),
                Pair("permission.SYSTEM_OVERLAY_WINDOW", 58),
                Pair("permission.SYSTEM_UI_VISIBILITY_EXTENSION", 593),
                Pair("permission.ScanResultReceiver", 298),
                Pair("permission.TRANSACTION_EVENT", 398),
                Pair("permission.TRANSMIT_IR", 168),
                Pair("permission.TRIGGER_UPLOAD", 520),
                Pair("permission.UA_DATA", 79),
                Pair("permission.UEMOJI", 463),
                Pair("permission.UNINSTALL_PACKAGES", 472),
                Pair("permission.UNINSTALL_SHORTCUT", 23),
                Pair("permission.UPDATE_APP_OPS_STATS", 72),
                Pair("permission.UPDATE_BADGE", 354),
                Pair("permission.UPDATE_COUNT", 250),
                Pair("permission.UPDATE_DEVICE_STATS", 192),
                Pair("permission.UPDATE_SHORTCUT", 244),
                Pair("permission.USB", 320),
                Pair("permission.USEFMRADIO", 539),
                Pair("permission.USE_CREDENTIALS", 101),
                Pair("permission.USE_DEVICE_CREDENTIALS", 288),
                Pair("permission.USE_FINGERPRINT", 259),
                Pair("permission.USE_SDK.com.tencent.tmgp.sgame.KingsGlory", 533),
                Pair("permission.USE_SIP", 187),
                Pair("permission.USE_SOCIALCOMPONENT", 436),
                Pair("permission.USE_SOCIALSERVICE", 266),
                Pair("permission.VIBRATE", 56),
                Pair("permission.VOIP_BROADCAST_VOIP_INTENTS", 507),
                Pair("permission.VOIP_INTERFACE", 182),
                Pair("permission.VOIP_SHOW_INCOMING_CALL", 512),
                Pair("permission.WEIBO_SDK_PERMISSION", 579),
                Pair("permission.WIFI_STATE", 347),
                Pair("permission.WRITE", 223),
                Pair("permission.WRITE_APN_SETTING", 307),
                Pair("permission.WRITE_APN_SETTINGS", 42),
                Pair("permission.WRITE_APN_STORAGE", 225),
                Pair("permission.WRITE_ATTACHMENT", 393),
                Pair("permission.WRITE_BADGES", 378),
                Pair("permission.WRITE_CALENDAR", 199),
                Pair("permission.WRITE_CALL_LOG", 175),
                Pair("permission.WRITE_CALL_SETTINGS", 395),
                Pair("permission.WRITE_CLIPS", 220),
                Pair("permission.WRITE_CONTACTS", 97),
                Pair("permission.WRITE_EPG_DATA", 361),
                Pair("permission.WRITE_EXTERNAL_STORAG", 368),
                Pair("permission.WRITE_EXTERNAL_STORAGE", 64),
                Pair("permission.WRITE_GMAIL", 396),
                Pair("permission.WRITE_HISTORY_BOOKMARKS", 270),
                Pair("permission.WRITE_INTERNAL_STORAGE", 236),
                Pair("permission.WRITE_LOCAL_THEME", 306),
                Pair("permission.WRITE_LOGS", 190),
                Pair("permission.WRITE_MEDIA_STORAGE", 76),
                Pair("permission.WRITE_ONLY", 120),
                Pair("permission.WRITE_OWNER_DATA", 104),
                Pair("permission.WRITE_PROFILE", 85),
                Pair("permission.WRITE_PUSHINFOPROVIDER.com.fy.tnzbsq", 549),
                Pair("permission.WRITE_PUSHINFOPROVIDER.com.myxianwen.nanguozaobao", 576),
                Pair("permission.WRITE_PUSHINFOPROVIDER.com.nd.android.pandahome2", 588),
                Pair("permission.WRITE_PUSHINFOPROVIDER.com.tv.kuaisou", 580),
                Pair("permission.WRITE_RECORD_AUDIO", 178),
                Pair("permission.WRITE_SECURE_SETTINGS", 68),
                Pair("permission.WRITE_SETTINGS", 4),
                Pair("permission.WRITE_SMS", 37),
                Pair("permission.WRITE_SOCIAL_DATABASE", 376),
                Pair("permission.WRITE_SOCIAL_STREAM", 158),
                Pair("permission.WRITE_TASKS", 389),
                Pair("permission.WRITE_TING_MP3", 405),
                Pair("permission.WRITE_UNREAD", 215),
                Pair("permission.WRITE_USAGESTATS", 545),
                Pair("permission.WRITE_USER_DICTIONARY", 337),
                Pair("permission.WloginProvider.READ", 265),
                Pair("permission.WloginProvider.WRITE", 264),
                Pair("permission.access_network_state", 540),
                Pair("permission.access_wifi_state", 406),
                Pair("permission.account", 553),
                Pair("permission.account.changed", 292),
                Pair("permission.account.sync", 253),
                Pair("permission.activityCalled", 273),
                Pair("permission.air.escapegamestudio.AntarcticDolphinEscape.permission.C2D_MESSAGE", 485),
                Pair("permission.android.hardware.sensor.accelerometer", 583),
                Pair("permission.appradio.AAM2", 500),
                Pair("permission.appradio.ADVANCED_APPMODE", 321),
                Pair("permission.avosclous.PUSH", 294),
                Pair("permission.broadcast", 279),
                Pair("permission.c2dm.permission.RECEIVE", 481),
                Pair("permission.cleandroid_cn", 363),
                Pair("permission.clear_sdk", 110),
                Pair("permission.clear_sdk_lds", 554),
                Pair("permission.com.airmailes.read", 470),
                Pair("permission.com.airmailes.write", 491),
                Pair("permission.downloadservice", 359),
                Pair("permission.downloadservice_nfc", 571),
                Pair("permission.mewidget_contact", 353),
                Pair("permission.mkiller.ASSIST_MSAFE", 278),
                Pair("permission.mount_unmount_filesystems", 423),
                Pair("permission.network", 446),
                Pair("permission.pcsync", 456),
                Pair("permission.prod.SYSTEM_COMMUNICATION", 381),
                Pair("permission.profiler.SENSOR_BROADCAST_RECEIVE", 513),
                Pair("permission.profiler.TRIGGER_SENSOR_BROADCAST_RECEIVE", 504),
                Pair("permission.pushnotify", 360),
                Pair("permission.sec.ENTERPRISE_DEVICE_ADMIN", 268),
                Pair("permission.sec.MDM_APP_MGMT", 460),
                Pair("permission.sec.MDM_BLUETOOTH", 523),
                Pair("permission.sec.MDM_BROWSER_SETTINGS", 450),
                Pair("permission.sec.MDM_CERTIFICATE", 352),
                Pair("permission.sec.MDM_ENTERPRISE_VPN", 516),
                Pair("permission.sec.MDM_EXCHANGE", 462),
                Pair("permission.sec.MDM_FIREWALL", 454),
                Pair("permission.sec.MDM_HW_CONTROL", 461),
                Pair("permission.sec.MDM_INVENTORY", 519),
                Pair("permission.sec.MDM_KIOSK_MODE", 479),
                Pair("permission.sec.MDM_LOCATION", 489),
                Pair("permission.sec.MDM_PHONE_RESTRICTION", 402),
                Pair("permission.sec.MDM_REMOTE_CONTROL", 447),
                Pair("permission.sec.MDM_RESTRICTION", 494),
                Pair("permission.sec.MDM_ROAMING", 478),
                Pair("permission.sec.MDM_SECURITY", 290),
                Pair("permission.sec.MDM_VPN", 499),
                Pair("permission.sec.MDM_WIFI", 492),
                Pair("permission.watermark", 409),
                Pair("permission.write_apn_settings", 407),
            )

            with(Dispatchers.IO) {
                return getAllPackages(context.packageManager)
                    .filter {
                        checkPermission(it, neededPermissions)
                    }
            }
        }

        private suspend fun checkPermission(
            packageInfo: PackageInfo,
            neededPermissions: List<Pair<String, Int>>
        ): Boolean {
            mapPermissions(packageInfo.requestedPermissions, neededPermissions)
            return false
        }

        private fun getAllPackages(packageManager: PackageManager): List<PackageInfo> {
            return packageManager
                .getInstalledPackages(PackageManager.GET_PERMISSIONS)
                .filter {
                    it.requestedPermissions != null && (
                            it.applicationInfo.flags.and(ApplicationInfo.FLAG_SYSTEM) != ApplicationInfo.FLAG_SYSTEM)
                }
        }

        private fun mapPermissions(permissions: Array<String>, neededPermissions: List<Pair<String, Int>>): FloatArray {
            val array = FloatArray(neededPermissions.size) { 0f }

            if (neededPermissions.isEmpty() || permissions.isEmpty()) {
                return array
            }

            val neededPermissionsIterator = neededPermissions.iterator()
            val permissionsIterator = permissions.sorted().iterator()

            var currentNeeded = neededPermissionsIterator.next()
            var currentHave = permissionsIterator.next()

            while (true) {
                if (currentNeeded.first < currentHave) {
                    if (!neededPermissionsIterator.hasNext())
                        break

                    currentNeeded = neededPermissionsIterator.next()

                } else if (currentNeeded.first > currentHave) {
                    if (!permissionsIterator.hasNext())
                        break

                    currentHave = permissionsIterator.next()

                } else {
                    array[currentNeeded.second] = 1f
                    if (!neededPermissionsIterator.hasNext() || !permissionsIterator.hasNext())
                        break

                    currentHave = permissionsIterator.next()
                    currentNeeded = neededPermissionsIterator.next()
                }
            }

            return array
        }
    }
}
